feat: convert spelling check to a standard check targets
input-output-hk/catalyst-ci pull request #118
Opened 2023-12-01 16:47 UTC by apskhem

# Description

## Related Issue(s)

> Closes #115 

## Description of Changes

Make spelling check conform to check target pattern

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

2023-12-05 09:29 UTC, Mr-Leshiy requested changes

2023-12-05 09:29 UTC, Mr-Leshiy commented on docs/src/guides/spelling.md
> +## Project Words
I would also add a note that it is possible to extend this list of words for each specific file, which we are broadly using.
```
cspell: words <words>
```

Examples :
- https://github.com/input-output-hk/catalyst-ci/blob/c2f7d03c6c7c7ed5227e3398efab4b1d6c7d1508/earthly/docs/Earthfile#L3
- https://github.com/input-output-hk/catalyst-ci/blob/c2f7d03c6c7c7ed5227e3398efab4b1d6c7d1508/docs/src/guides/languages/postgresql.md#L12

2023-12-05 09:29 UTC, Mr-Leshiy commented on Earthfile
>  spell-check:
let's rename this target to `local-spell-check`

2023-12-05 09:29 UTC, Mr-Leshiy commented on Earthfile
> +check-spelling:
rename it to just `spell-check`

2023-12-05 09:29 UTC, Mr-Leshiy commented on docs/src/guides/spelling.md
> +---
Also provide an Earthly example how to play with spell checking.
You can just copy that code which you have already written with `check-spelling` and `check` target

2023-12-05 09:29 UTC, Mr-Leshiy commented on earthly/cspell/Earthfile
> +CHECK:
Let's rename `CSPELL_LOCALLY` to `LOCAL_CHECK` or `CHECK_LOCALLY`

2023-12-05 10:01 UTC, Mr-Leshiy commented
BTW, I think we should add this `check` target to the separate Earthfile, for example to the `earthly/cspell/Earthfile`. 
So the idea is to run spell checks and markdown checks separately in different job, rather than in one as we will put it under the similar `check` target inside the root `Earthfile`. 
Because if we will put it under the same target like this
```
check:
    BUILD +check-spelling
    BUILD +check-markdown
```
if spell check will fail, markdown check will not even run, what we don't want

@stevenj

2023-12-06 11:28 UTC, Mr-Leshiy commented on docs/src/guides/spellcheck.md
> +## Using the spell checking
Also don't forget to add about local spell checking run

2023-12-06 14:08 UTC, stevenj requested changes

2023-12-06 15:32 UTC, stevenj approved these changes
LGTM

2023-12-06 15:33 UTC, merged