chore: Add catalyst-pallas (pallas lib fork repo) to the allowed sources list in deny.toml
input-output-hk/catalyst-ci pull request #159
Opened 2024-01-17 14:01 UTC by FelipeRosa

2024-01-17 19:42 UTC, Mr-Leshiy submitted a review, later dismissed
LGTM

2024-01-18 04:20 UTC, stevenj commented on earthly/rust/stdcfgs/deny.toml
> +github = ["input-output-hk"]
I would prefer we don't do this, for the pallas fork especially.
The pallas fork should not be long lived, we should be upstreaming any changes we do ASAP.
If we DO use a github repo directly, I would also rather we specifically declare it and not a whole organization even if its us.

2024-01-18 04:22 UTC, stevenj requested changes
We should not be allowing whole organizations.
In the case of Pallas this should not be needed as we should be upstreaming any changes we make, not maintaining them long term.

2024-01-18 14:24 UTC, stevenj approved these changes
LGTM

2024-01-18 14:32 UTC, merged